### ISSUE TITLE
Support laravel 8

### ISSUE THREAD

**Issue by chelsEg** [chocofamilyme/laravel-tarantool#18]
Hello.

Do you plan support Laravel 8?

**Comment by AidynMakhataev** [comment]
I will release soon new version with laravel 8 support

> Hello.
> 
> Do you plan support Laravel 8?

**Comment by AidynMakhataev** [comment]
> Hello.
> 
> Do you plan support Laravel 8?

Laravel 8 is available with new version, check it out

https://github.com/chocofamilyme/laravel-tarantool/releases/tag/1.0.0
