### ISSUE TITLE
Does it support Laravel Lumen ?

### ISSUE THREAD

**Issue by measproem** [chocofamilyme/laravel-tarantool#22]
Hello Chocofamilyme,

I would like to know does laravel-tarantool support Laravel Lumen ?

**Comment by AidynMakhataev** [comment]
Hello @meashsim 

Yeah, it should work on Lumen. You need to manually register our ServiceProvider and enable Eloquent in `bootstrap/app.php`

```
$app->register(Chocofamily\Tarantool\ServiceProvider::class);

$app->withEloquent();
```
